### ISSUE TITLE
Make sourcefinding.py work without apercal.

### ISSUE THREAD

**Issue by kmhess** [kmhess/sourcefinding#9]
Probably need to reorganize modules/functions.

Traceback (most recent call last):
File "sourcefinding.py", line 4, in <module>
from src import checkmasks
File "/net/diva/scratch1/jfalcon/Apertif_analysis/sourcefinding-master/src/checkmasks.py", line 4, in <module>
from modules.functions import chan2freq
File "/net/diva/scratch1/jfalcon/Apertif_analysis/sourcefinding-master/modules/functions.py", line 7, in <module>
from .PB_correction_happili2 import *
File "/net/diva/scratch1/jfalcon/Apertif_analysis/sourcefinding-master/modules/PB_correction_happili2.py", line 17, in <module>
from apercal.libs import lib
ImportError: No module named apercal.libs

**Comment by kmhess** [comment]
This has been resolved.  sourcefinding.py now runs without apercal.
